Repository sssmoker/SMOKER-BE, pull requests merged in 2025-02, with the labels that each got.

#81 [Refactor] 모달 띄우기 url 토큰 추출 오류 수정하기
  src/main/java/com/ssmoker/smoker/domain/smokingArea/controller/SmokingAreaController.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/service/SmokingAreaService.java
  src/main/java/com/ssmoker/smoker/global/configuration/SecurityConfig.java
  src/main/java/com/ssmoker/smoker/global/security/filter/JwtRequestFilter.java
Labels: refactor

#90 [Fix] url 중복 해결
  src/main/java/com/ssmoker/smoker/domain/updatedHistory/controller/UpdatedHistoryController.java
Labels: fix

#94 [Feat] 저장된 흡연구역 기능 구현
  src/main/java/com/ssmoker/smoker/domain/smokingArea/controller/SavedSmokingAreaController.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/domain/SavedSmokingArea.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/dto/MapResponse.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/repository/SavedSmokingAreaRepository.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/service/SmokingAreaService.java
  src/main/java/com/ssmoker/smoker/global/exception/code/ErrorStatus.java
Labels: feature

#96 [Refactor] 흡연 구역 검색 기능 수정하기
  src/main/java/com/ssmoker/smoker/domain/smokingArea/service/SmokingAreaService.java
Labels: refactor

#98 [Feat] 자주 묻는 질문 조회 api 추가
  src/main/java/com/ssmoker/smoker/domain/question/controller/QuestionContoller.java
  src/main/java/com/ssmoker/smoker/domain/question/converter/QuestionConverter.java
  src/main/java/com/ssmoker/smoker/domain/question/domain/Question.java
  src/main/java/com/ssmoker/smoker/domain/question/dto/QuestionResponse.java
  src/main/java/com/ssmoker/smoker/domain/question/repository/QuestionRepository.java
  src/main/java/com/ssmoker/smoker/domain/question/service/QuestionService.java
  src/main/java/com/ssmoker/smoker/global/apiPayload/code/SuccessStatus.java
  src/main/java/com/ssmoker/smoker/global/configuration/SecurityConfig.java
  src/main/java/com/ssmoker/smoker/global/exception/code/ErrorStatus.java
  src/main/java/com/ssmoker/smoker/global/security/filter/JwtRequestFilter.java
Labels: feature

#99 [Refactor] 흡연 구역 검색 기능_1km 반경 조건 삭제하기
  src/main/java/com/ssmoker/smoker/domain/smokingArea/repository/SmokingAreaRepository.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/service/SmokingAreaService.java
Labels: refactor

#104 [Fix] CORS 설정
  src/main/java/com/ssmoker/smoker/global/configuration/SecurityConfig.java
Labels: fix

#106 [Refactor] filter 정렬 한글로 변경하기
  src/main/java/com/ssmoker/smoker/domain/smokingArea/service/SmokingAreaService.java
Labels: refactor

#109 [Refactor] 닉네임 중복 제한 삭제
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberServiceImpl.java
  src/main/java/com/ssmoker/smoker/global/exception/code/ErrorStatus.java
Labels: refactor, fix

#111 [Fix] JwtRequestFilter 수정
  src/main/java/com/ssmoker/smoker/global/security/filter/JwtRequestFilter.java
Labels: fix
