Repository sssmoker/SMOKER-BE, pull requests merged in 2025-01, with the labels that each got.

#8 [Feat] 보안 관련 기본 설정
  .gitignore
  build.gradle
  src/main/java/com/ssmoker/smoker/SmokerApplication.java
  src/main/resources/application.yml
Labels: feature, docs

#17 [Feat] Kakao, Google 소셜 로그인, jwt 토큰 발급 api 구현
  build.gradle
  src/main/java/com/ssmoker/smoker/domain/member/controller/MemberController.java
  src/main/java/com/ssmoker/smoker/domain/member/domain/Member.java
  src/main/java/com/ssmoker/smoker/domain/member/dto/AuthRequestDTO.java
  src/main/java/com/ssmoker/smoker/domain/member/dto/AuthResponseDTO.java
  src/main/java/com/ssmoker/smoker/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/ssmoker/smoker/domain/member/repository/MemberRepository.java
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberService.java
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberServiceImpl.java
  src/main/java/com/ssmoker/smoker/global/apiPayload/code/SuccessStatus.java
  src/main/java/com/ssmoker/smoker/global/exception/AuthException.java
  src/main/java/com/ssmoker/smoker/global/exception/code/ErrorStatus.java
  src/main/java/com/ssmoker/smoker/security/SecurityConfig.java
  src/main/java/com/ssmoker/smoker/security/authDTO/GoogleProfile.java
  src/main/java/com/ssmoker/smoker/security/authDTO/KakaoProfile.java
  src/main/java/com/ssmoker/smoker/security/authDTO/OAuthToken.java
  src/main/java/com/ssmoker/smoker/security/converter/AuthConverter.java
  src/main/java/com/ssmoker/smoker/security/filter/JwtRequestFilter.java
  src/main/java/com/ssmoker/smoker/security/handler/annotation/AuthUser.java
  src/main/java/com/ssmoker/smoker/security/handler/resolver/AuthUserArgumentResolver.java
  src/main/java/com/ssmoker/smoker/security/principal/PrincipalDetails.java
  src/main/java/com/ssmoker/smoker/security/principal/PrincipalDetailsService.java
  src/main/java/com/ssmoker/smoker/security/provider/GoogleAuthProvider.java
  src/main/java/com/ssmoker/smoker/security/provider/JwtTokenProvider.java
  src/main/java/com/ssmoker/smoker/security/provider/KakaoAuthProvider.java
  src/main/resources/application.yml
Labels: feature

#22 [Feat] 흡연 구역 지도 marker 표시
  src/main/java/com/ssmoker/smoker/domain/smokingArea/controller/SmokingAreaController.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/domain/Location.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/domain/SmokingArea.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/dto/MapResponse.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/dto/SmokingAreaMarkersResponse.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/repository/SmokingAreaRepository.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/service/SmokingAreaService.java
  src/main/java/com/ssmoker/smoker/global/apiPayload/code/SuccessStatus.java
  src/main/java/com/ssmoker/smoker/security/SecurityConfig.java
Labels: feature

#26 [Fix] ArgumentResolver 수정한다.
  src/main/java/com/ssmoker/smoker/TestController.java
  src/main/java/com/ssmoker/smoker/domain/member/controller/MemberController.java
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberServiceImpl.java
  src/main/java/com/ssmoker/smoker/global/configuration/SecurityConfig.java
  src/main/java/com/ssmoker/smoker/global/configuration/WebConfig.java
  src/main/java/com/ssmoker/smoker/global/security/authDTO/GoogleProfile.java
  src/main/java/com/ssmoker/smoker/global/security/authDTO/KakaoProfile.java
  src/main/java/com/ssmoker/smoker/global/security/authDTO/OAuthToken.java
  src/main/java/com/ssmoker/smoker/global/security/converter/AuthConverter.java
  src/main/java/com/ssmoker/smoker/global/security/exception/AuthException.java
  src/main/java/com/ssmoker/smoker/global/security/filter/JwtRequestFilter.java
  src/main/java/com/ssmoker/smoker/global/security/handler/annotation/AuthUser.java
  src/main/java/com/ssmoker/smoker/global/security/handler/resolver/AuthUserArgumentResolver.java
  src/main/java/com/ssmoker/smoker/global/security/principal/PrincipalDetails.java
  src/main/java/com/ssmoker/smoker/global/security/principal/PrincipalDetailsService.java
  src/main/java/com/ssmoker/smoker/global/security/provider/GoogleAuthProvider.java
  src/main/java/com/ssmoker/smoker/global/security/provider/JwtTokenProvider.java
  src/main/java/com/ssmoker/smoker/global/security/provider/KakaoAuthProvider.java
Labels: :lady_beetle: bug

#28 [Refactor] jwt 토큰 관련 수정
  build.gradle
  src/main/java/com/ssmoker/smoker/domain/member/controller/MemberController.java
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberService.java
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberServiceImpl.java
  src/main/java/com/ssmoker/smoker/domain/token/controller/TokenController.java
  src/main/java/com/ssmoker/smoker/domain/token/domain/Token.java
  src/main/java/com/ssmoker/smoker/domain/token/repository/TokenRepository.java
  src/main/java/com/ssmoker/smoker/domain/token/service/TokenService.java
  src/main/java/com/ssmoker/smoker/global/configuration/SecurityConfig.java
  src/main/java/com/ssmoker/smoker/global/exception/code/ErrorStatus.java
  src/main/java/com/ssmoker/smoker/global/security/authDTO/AuthRequestDTO.java
  src/main/java/com/ssmoker/smoker/global/security/authDTO/AuthResponseDTO.java
  src/main/java/com/ssmoker/smoker/global/security/controller/AuthController.java
  src/main/java/com/ssmoker/smoker/global/security/controller/AuthService.java
  src/main/java/com/ssmoker/smoker/global/security/converter/AuthConverter.java
  src/main/java/com/ssmoker/smoker/global/security/filter/JwtRequestFilter.java
  src/main/java/com/ssmoker/smoker/global/security/handler/resolver/AuthUserArgumentResolver.java
  src/main/java/com/ssmoker/smoker/global/security/provider/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: refactor

#31 [Feat] 회원탈퇴 구현
  src/main/java/com/ssmoker/smoker/domain/token/controller/TokenController.java
  src/main/java/com/ssmoker/smoker/domain/token/service/TokenService.java
  src/main/java/com/ssmoker/smoker/global/security/controller/AuthController.java
  src/main/resources/application.yml
Labels: feature

#33 [Chore] S3 세팅 및 예시 작성
  build.gradle
  src/main/java/com/ssmoker/smoker/TestController.java
  src/main/java/com/ssmoker/smoker/domain/member/controller/MemberController.java
  src/main/java/com/ssmoker/smoker/domain/review/domain/Review.java
  src/main/java/com/ssmoker/smoker/domain/review/exception/ReviewPageNumberException.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/controller/SmokingAreaController.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/domain/SmokingArea.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/service/SmokingAreaService.java
  src/main/java/com/ssmoker/smoker/global/aws/s3/AmazonS3Manager.java
  src/main/java/com/ssmoker/smoker/global/configuration/AmazonConfig.java
  src/main/java/com/ssmoker/smoker/global/security/filter/JwtRequestFilter.java
  src/main/java/com/ssmoker/smoker/test/Test.java
  src/main/java/com/ssmoker/smoker/test/TestController.java
  src/main/java/com/ssmoker/smoker/test/TestRepository.java
  src/main/java/com/ssmoker/smoker/test/TestRequestDto.java
  src/main/resources/application.yml
Labels: feature, setting

#36 [Feat] 흡연 구역 목록 조회하기
  src/main/java/com/ssmoker/smoker/domain/member/domain/Member.java
  src/main/java/com/ssmoker/smoker/domain/review/repository/ReviewRepository.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/controller/SmokingAreaController.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/domain/SavedSmokingArea.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/domain/SmokingArea.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/dto/MapResponse.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/repository/SmokingAreaRepository.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/service/SmokingAreaService.java
  src/main/java/com/ssmoker/smoker/global/exception/code/ErrorStatus.java
Labels: feature

#40 [Feat] 프로필 변경 기능 구현
  src/main/java/com/ssmoker/smoker/domain/member/controller/MemberController.java
  src/main/java/com/ssmoker/smoker/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/ssmoker/smoker/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/ssmoker/smoker/domain/member/repository/MemberRepository.java
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberService.java
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberServiceImpl.java
  src/main/java/com/ssmoker/smoker/global/apiPayload/code/SuccessStatus.java
  src/main/java/com/ssmoker/smoker/global/exception/code/ErrorStatus.java
Labels: feature

#43 [Refactor] generateProfileKeyName 추가, 프로필 이미지 업로드 경로 수정
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberServiceImpl.java
  src/main/java/com/ssmoker/smoker/global/aws/s3/AmazonS3Manager.java
  src/main/java/com/ssmoker/smoker/global/configuration/AmazonConfig.java
  src/main/resources/application.yml
Labels: refactor

#44 [Feat] 마이페이지 회원 정보 조회 api 구현
  src/main/java/com/ssmoker/smoker/domain/member/controller/MemberController.java
  src/main/java/com/ssmoker/smoker/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberService.java
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberServiceImpl.java
  src/main/java/com/ssmoker/smoker/global/apiPayload/code/SuccessStatus.java
Labels: feature

#50 [Feat] 마이페이지 내가 작성한 리뷰 조회 api
  src/main/java/com/ssmoker/smoker/domain/member/controller/MemberController.java
  src/main/java/com/ssmoker/smoker/domain/member/converter/MemberConverter.java
  src/main/java/com/ssmoker/smoker/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberService.java
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberServiceImpl.java
  src/main/java/com/ssmoker/smoker/domain/review/repository/ReviewRepository.java
  src/main/java/com/ssmoker/smoker/global/apiPayload/code/SuccessStatus.java
Labels: feature

#51 [Feat] 나의 업데이트 히스토리 조회 API 추가
  src/main/java/com/ssmoker/smoker/domain/member/controller/MemberController.java
  src/main/java/com/ssmoker/smoker/domain/member/converter/MemberConverter.java
  src/main/java/com/ssmoker/smoker/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberService.java
  src/main/java/com/ssmoker/smoker/domain/member/service/MemberServiceImpl.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/controller/SmokingAreaController.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/service/SmokingAreaService.java
  src/main/java/com/ssmoker/smoker/domain/updatedHistory/domain/Action.java
  src/main/java/com/ssmoker/smoker/domain/updatedHistory/domain/UpdatedHistory.java
  src/main/java/com/ssmoker/smoker/domain/updatedHistory/repository/UpdatedHistoryRepository.java
  src/main/java/com/ssmoker/smoker/global/apiPayload/code/SuccessStatus.java
  src/main/java/com/ssmoker/smoker/global/security/filter/JwtRequestFilter.java
Labels: feature, refactor

#53 [Feat] 흡연구역 목록 검색
  src/main/java/com/ssmoker/smoker/domain/review/repository/ReviewRepository.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/controller/SmokingAreaController.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/dto/KaKaoApiResponse.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/dto/MapResponse.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/dto/SmokingAreaRequest.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/repository/SmokingAreaRepository.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/service/KaKaoApiService.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/service/SmokingAreaService.java
  src/main/java/com/ssmoker/smoker/global/security/filter/JwtRequestFilter.java
Labels: feature

#56 [Feat] 공지사항 목록 조회하기
  src/main/java/com/ssmoker/smoker/domain/notice/controller/NoticeController.java
  src/main/java/com/ssmoker/smoker/domain/notice/dto/NoticeResponse.java
  src/main/java/com/ssmoker/smoker/domain/notice/exception/NoticeNotFoundException.java
  src/main/java/com/ssmoker/smoker/domain/notice/repository/NoticeRepository.java
  src/main/java/com/ssmoker/smoker/domain/notice/service/NoticeService.java
  src/main/java/com/ssmoker/smoker/global/apiPayload/code/SuccessStatus.java
  src/main/java/com/ssmoker/smoker/global/exception/code/ErrorStatus.java
  src/main/java/com/ssmoker/smoker/global/security/filter/JwtRequestFilter.java
Labels: feature

#58 [Refactor] Member 관련 수정
  src/main/java/com/ssmoker/smoker/domain/member/domain/Member.java
  src/main/java/com/ssmoker/smoker/global/security/converter/AuthConverter.java
Labels: refactor

#63 [Feat] 공지사항 세부 사항 조회하기
  src/main/java/com/ssmoker/smoker/domain/notice/controller/NoticeController.java
  src/main/java/com/ssmoker/smoker/domain/notice/dto/NoticeResponse.java
  src/main/java/com/ssmoker/smoker/domain/notice/service/NoticeService.java
  src/main/java/com/ssmoker/smoker/global/configuration/SecurityConfig.java
  src/main/java/com/ssmoker/smoker/global/security/filter/JwtRequestFilter.java
Labels: feature

#67 [Feat] OCR 검증 및 흡연 구역 이미지 저장을 구현한다.
  .gitignore
  build.gradle
  gradlew
  src/main/java/com/ssmoker/smoker/domain/smokingArea/controller/SmokingAreaController.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/service/GoogleVisionOCRService.java
  src/main/java/com/ssmoker/smoker/global/apiPayload/code/SuccessStatus.java
  src/main/java/com/ssmoker/smoker/global/aws/s3/AmazonS3Manager.java
  src/main/java/com/ssmoker/smoker/global/exception/code/ErrorStatus.java
Labels: feature

#71 [Refactor] dto에 imageUrl 필드 추가하기
  src/main/java/com/ssmoker/smoker/domain/smokingArea/dto/MapResponse.java
  src/main/java/com/ssmoker/smoker/domain/smokingArea/service/SmokingAreaService.java
Labels: refactor
